AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  achiever-api

  Sample SAM Template for achiever-api

Globals:
  Function:
    Timeout: 10

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        today:
          Type: Api
          Properties:
            Path: /today
            Method: get
        tomorrow:
          Type: Api
          Properties:
            Path: /tomorrow
            Method: get

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage for API function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ApiFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ApiFunction.Arn
  ApiFunctionRole :
    Description: "Implicit IAM Role created for API function"
    Value: !GetAtt ApiFunctionRole.Arn
