AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  achiever-api

  Sample SAM Template for achiever-api

Globals:
  Function:
    Timeout: 3

Resources:
  DailyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: daily/
      Handler: daily.handler
      Runtime: nodejs12.x
      Events:
        root:
          Type: Api
          Properties:
            Path: /daily
            Method: get

Outputs:
  DailyApi:
    Description: "API Gateway endpoint URL for Prod stage for Daily function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  DailyFunction:
    Description: "Daily Lambda Function ARN"
    Value: !GetAtt DailyFunction.Arn
  DailyFunctionIamRole:
    Description: "Implicit IAM Role created for Daily function"
    Value: !GetAtt DailyFunctionRole.Arn
