AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  achiever-api

  Sample SAM Template for achiever-api

Globals:
  Function:
    Timeout: 10

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: index.handler
      Runtime: nodejs16.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: DailyTable
      Environment:
        Variables:
          DAILY_TABLE:
            Ref: DailyTable
      Events:
        GetProxy:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: get
        LoadScheduledEvent:
          Type: Schedule
          Name: LoadDaily
          Properties:
            Schedule: cron(01 00 * * ? *)
  DailyTable:
    Type: AWS::Serverless::SimpleTable

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage for API function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ApiFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ApiFunction.Arn
  ApiFunctionRole :
    Description: "Implicit IAM Role created for API function"
    Value: !GetAtt ApiFunctionRole.Arn
