name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: SAM Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM ci
        run: cd daily && npm ci
      - name: SAM Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: sam deploy --stack-name achiever-api --no-fail-on-empty-changeset
