name: Validate
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: SAM Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM ci
        run: cd api && npm ci
      - name: SAM Build
        run: sam build
  test:
    name: NPM Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM ci
        run: cd api && npm ci
      - name: NPM Test
        env:
          DPS_REPORTS_TOKEN: ${{ secrets.DPS_REPORTS_TOKEN }}
          GW2_TOKEN: ${{ secrets.GW2_TOKEN }}
        run: cd api && npm test
