name: Validate
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: SAM Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM ci
        run: cd daily && npm ci
      - name: SAM Build
        run: sam build
  test:
    name: NPM Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM ci
        run: cd daily && npm ci
      - name: NPM Test
        run: cd daily && npm test
